export const mockProducts = [
  {
    name: "Product 1",
    inPrice: "10",
    price: "15",
    inStock: "100",
    description: "High-quality product 1",
  },
  {
    name: "Product 2",
    inPrice: "20",
    price: "30",
    inStock: "50",
    description: "Excellent product 2",
  },
  {
    name: "Product 3",
    inPrice: "5",
    price: "8",
    inStock: "200",
    description: "Affordable product 3",
  },
  {
    name: "Product 4",
    inPrice: "12",
    price: "18",
    inStock: "150",
    description: "Reliable product 4",
  },
  {
    name: "Product 5",
    inPrice: "8",
    price: "12",
    inStock: "300",
    description: "Popular product 5",
  },
  {
    name: "Product 6",
    inPrice: "14",
    price: "22",
    inStock: "75",
    description: "High-performance product 6",
  },
  {
    name: "Product 7",
    inPrice: "25",
    price: "35",
    inStock: "60",
    description: "Durable product 7",
  },
  {
    name: "Product 8",
    inPrice: "7",
    price: "10",
    inStock: "500",
    description: "Compact product 8",
  },
  {
    name: "Product 9",
    inPrice: "30",
    price: "45",
    inStock: "20",
    description: "Premium product 9",
  },
  {
    name: "Product 10",
    inPrice: "18",
    price: "27",
    inStock: "90",
    description: "Eco-friendly product 10",
  },
  {
    name: "Product 11",
    inPrice: "22",
    price: "33",
    inStock: "120",
    description: "Stylish product 11",
  },
  {
    name: "Product 12",
    inPrice: "16",
    price: "24",
    inStock: "80",
    description: "Ergonomic product 12",
  },
  {
    name: "Product 13",
    inPrice: "9",
    price: "14",
    inStock: "200",
    description: "Lightweight product 13",
  },
  {
    name: "Product 14",
    inPrice: "27",
    price: "40",
    inStock: "65",
    description: "Versatile product 14",
  },
  {
    name: "Product 15",
    inPrice: "19",
    price: "29",
    inStock: "110",
    description: "Innovative product 15",
  },
  {
    name: "Product 16",
    inPrice: "13",
    price: "19",
    inStock: "140",
    description: "Classic product 16",
  },
  {
    name: "Product 17",
    inPrice: "6",
    price: "9",
    inStock: "250",
    description: "Budget-friendly product 17",
  },
  {
    name: "Product 18",
    inPrice: "11",
    price: "16",
    inStock: "180",
    description: "Advanced product 18",
  },
  {
    name: "Product 19",
    inPrice: "24",
    price: "36",
    inStock: "70",
    description: "Sophisticated product 19",
  },
  {
    name: "Product 20",
    inPrice: "15",
    price: "22",
    inStock: "130",
    description: "High-capacity product 20",
  },
  {
    name: "Product 21",
    inPrice: "5",
    price: "8",
    inStock: "400",
    description: "Compact product 21",
  },
  {
    name: "Product 22",
    inPrice: "28",
    price: "42",
    inStock: "55",
    description: "Elegant product 22",
  },
  {
    name: "Product 23",
    inPrice: "17",
    price: "25",
    inStock: "100",
    description: "Modern product 23",
  },
  {
    name: "Product 24",
    inPrice: "10",
    price: "15",
    inStock: "220",
    description: "User-friendly product 24",
  },
  {
    name: "Product 25",
    inPrice: "20",
    price: "30",
    inStock: "90",
    description: "Compact design product 25",
  },
  {
    name: "Product 26",
    inPrice: "8",
    price: "12",
    inStock: "350",
    description: "Stylish product 26",
  },
  {
    name: "Product 27",
    inPrice: "32",
    price: "48",
    inStock: "40",
    description: "High-end product 27",
  },
  {
    name: "Product 28",
    inPrice: "14",
    price: "21",
    inStock: "160",
    description: "Durable product 28",
  },
  {
    name: "Product 29",
    inPrice: "18",
    price: "26",
    inStock: "100",
    description: "Reliable product 29",
  },
  {
    name: "Product 30",
    inPrice: "9",
    price: "13",
    inStock: "300",
    description: "Compact product 30",
  },
  {
    name: "Product 31",
    inPrice: "21",
    price: "32",
    inStock: "85",
    description: "Feature-rich product 31",
  },
  {
    name: "Product 32",
    inPrice: "12",
    price: "18",
    inStock: "190",
    description: "Classic product 32",
  },
  {
    name: "Product 33",
    inPrice: "7",
    price: "11",
    inStock: "420",
    description: "Eco-friendly product 33",
  },
  {
    name: "Product 34",
    inPrice: "26",
    price: "39",
    inStock: "60",
    description: "Sleek product 34",
  },
  {
    name: "Product 35",
    inPrice: "15",
    price: "23",
    inStock: "140",
    description: "High-tech product 35",
  },
  {
    name: "Product 36",
    inPrice: "10",
    price: "14",
    inStock: "280",
    description: "Popular product 36",
  },
  {
    name: "Product 37",
    inPrice: "19",
    price: "28",
    inStock: "120",
    description: "Professional product 37",
  },
  {
    name: "Product 38",
    inPrice: "13",
    price: "20",
    inStock: "170",
    description: "Innovative product 38",
  },
  {
    name: "Product 39",
    inPrice: "8",
    price: "12",
    inStock: "330",
    description: "Compact product 39",
  },
  {
    name: "Product 40",
    inPrice: "23",
    price: "34",
    inStock: "75",
    description: "Advanced product 40",
  },
  {
    name: "Product 41",
    inPrice: "6",
    price: "9",
    inStock: "500",
    description: "Lightweight product 41",
  },
  {
    name: "Product 42",
    inPrice: "29",
    price: "43",
    inStock: "50",
    description: "Luxury product 42",
  },
  {
    name: "Product 43",
    inPrice: "18",
    price: "26",
    inStock: "130",
    description: "Modern product 43",
  },
  {
    name: "Product 44",
    inPrice: "11",
    price: "17",
    inStock: "250",
    description: "Versatile product 44",
  },
  {
    name: "Product 45",
    inPrice: "24",
    price: "35",
    inStock: "65",
    description: "Ergonomic product 45",
  },
  {
    name: "Product 46",
    inPrice: "14",
    price: "20",
    inStock: "200",
    description: "Innovative product 46",
  },
  {
    name: "Product 47",
    inPrice: "9",
    price: "13",
    inStock: "310",
    description: "Compact product 47",
  },
  {
    name: "Product 48",
    inPrice: "20",
    price: "29",
    inStock: "90",
    description: "Premium product 48",
  },
  {
    name: "Product 49",
    inPrice: "12",
    price: "18",
    inStock: "180",
    description: "Classic product 49",
  },
  {
    name: "Product 50",
    inPrice: "5",
    price: "7",
    inStock: "600",
    description: "Affordable product 50",
  },
];
